#  settings
url = "http://localhost:8545"
network = "sokol" # "core" for the main and "sokol" for the test network

# mining-block-test settings
maxRounds = 5

# Sending txs test
addressTxTest1_sokol = "0x...dfcb"
passwordTxTest1_sokol = "password"
addressTxTest2_sokol = "0x...a72"
passwordTxTest2_sokol = "password"

addressTxTest1_core = "0x"
passwordTxTest1_core = "password"
addressTxTest2_core = "0x.."
passwordTxTest2_core = "password"

#Sending txs via public RPC test
keyStorePath1_sokol = "\path\a25...c.json"
addressPublicRpcTest1_sokol = "0x.."
passwordPublicRpcTest1_sokol = "password"

keyStorePath2_sokol = "\path\ab...3a.json"
addressPublicRpcTest2_sokol = "0x...."
passwordPublicRpcTest2_sokol = "password"

keyStorePath1_core = "\path\..json"
addressPublicRpcTest1_core = "0x..."
passwordPublicRpcTest1_core = "password"

keyStorePath2_core = "\path\a0c43...b.json"
addressPublicRpcTest2_core = "0x...."
passwordPublicRpcTest2_core = "password"

# Transaction settings
gasPrice = "1000000000"
simpleTransactionGas = "21000"
simpleTransactionCost = "21000000000000" # equals to gas multipty by gascost: 21000 * 1000000000
amountToSend = "20000000000"
miningReward = "1000000000000000000"
txsNumber = 10

# Reorgs settings
maxBlocksToSave = 20

#slack
slackWebHookUrl = 'https://hooks.slack.com/services/............token'
channel = 'monitor'

#Monitor
domainName = "http://localhost:3000/"